version: '3.9'
services:
  frontend:
    image: node:16.18
    container_name: digital_bank_app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    tty: true
    stdin_open: true
    command: bash -c "npm install -g npm@9.1.3 && npm run dev"
    restart: always
    depends_on:
      - backend
    networks:
      - virtual_wan_Front-to-Back
  backend:
    image: node:16.18
    container_name: digital_bank_app_backend
    build: ./backend
    # user: node
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    tty: true
    stdin_open: true
    command: bash -c "npm install -g npm@9.1.3 && chown -R root /app/backend && npm start"
    restart: always
    depends_on:
      - db
    ports:
      - 4001:4001
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_bank
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      API_PORT: 4001
    networks:
      - virtual_wan_Front-to-Back
      - virtual_lan_Back-to-DB
  postgres:
    image: postgres:14.2-alpine
    container_name: digital_bank_app_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - virtual_lan_Back-to-DB
    cap_add:
      - SYS_NICE
networks:
  # The presence of these objects is sufficient to define them
  virtual_wan_Front-to-Back: {}
  virtual_lan_Back-to-DB: {}

# As chaves `tty`, `stdin_open` e `command` fazem com que o container fique
# rodando em segundo plano, bem como tornam possível o uso do comando
# `docker attach`, já deixando o terminal atual acoplado ao container, direto
# no bash. Apesar disso, utilizar o attach mais de uma vez irá replicar o
# terminal, portanto é melhor utilizar o comando `docker exec`.

# A renomeação da rede padrão é feita pois caso contrário o nome da rede será
# o nome do diretório onde o arquivo atual se encontra, o que pode dificultar
# a listagem individual.
